import type { Metadata } from "next";
import Link from "next/link";
import { Footer } from "@/components/layout/Footer";
import { researchArticles } from "@/content/research";
import { site } from "@/content/site";

const title = "Research methodology";
const description =
  "Data sources, sample sizes, analysis methods, and published limits for Josh Blyskal's AI search research.";

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical: `${site.url}/research/methodology` },
  openGraph: {
    title,
    description,
    url: `${site.url}/research/methodology`,
    images: [{ url: site.ogImage, width: 1200, height: 630, alt: title }],
  },
};

const definitions = [
  {
    term: "Response",
    definition:
      "The answer returned by an AI product for one monitored prompt execution. A response may contain no citations or several.",
  },
  {
    term: "Citation",
    definition:
      "A source URL attributed or linked from an answer. Citation counts and response counts are different denominators.",
  },
  {
    term: "Query fanout",
    definition:
      "A search query generated by an answer engine from the user's prompt before it assembles a response.",
  },
  {
    term: "Domain overlap",
    definition:
      "The share of domains present in both compared source sets. It does not mean that the systems chose the same page or wrote the same answer.",
  },
] as const;

export default function ResearchMethodologyPage() {
  return (
    <div className="min-h-screen bg-background">
      <main className="mx-auto max-w-5xl px-6 pb-24 pt-10 md:pb-32">
        <nav className="flex flex-wrap items-center justify-between gap-5 font-mono text-[10px] uppercase tracking-widest">
          <Link href="/research" className="hover:text-accent">
            ← Research
          </Link>
          <Link href="/about" className="hover:text-accent">
            About Josh
          </Link>
        </nav>

        <header className="border-b-2 border-foreground pb-12 pt-24">
          <p className="font-mono text-xs uppercase tracking-[0.25em] text-accent">
            Disclosure record
          </p>
          <h1 className="mt-6 text-5xl font-display font-normal italic leading-none md:text-7xl">
            Research methodology
          </h1>
          <p className="mt-8 max-w-3xl font-body text-xl leading-relaxed text-foreground/75">
            These studies came from Profound's monitoring of live answer-engine outputs and focused
            experiments built on top of that dataset. This page records what each public source says
            about its sample and what it leaves out.
          </p>
        </header>

        <section className="border-b-2 border-foreground py-14">
          <h2 className="text-3xl font-display font-normal italic">Shared definitions</h2>
          <dl className="mt-8 divide-y divide-foreground/20 border-y border-foreground/20">
            {definitions.map(({ term, definition }) => (
              <div key={term} className="grid gap-2 py-5 md:grid-cols-[10rem_1fr] md:gap-8">
                <dt className="font-mono text-xs uppercase tracking-wider text-accent">{term}</dt>
                <dd className="font-body text-base leading-relaxed text-foreground/75">
                  {definition}
                </dd>
              </div>
            ))}
          </dl>
        </section>

        <section className="border-b-2 border-foreground py-14">
          <h2 className="text-3xl font-display font-normal italic">How to read the numbers</h2>
          <div className="mt-7 max-w-3xl space-y-6 font-body text-lg leading-relaxed text-foreground/80">
            <p>
              A top-line corpus and a sub-study are not interchangeable. The 250-million-response
              study contains smaller analyses of pages, URLs, citations, search results, and product
              pages. Each chart names the denominator that produced it.
            </p>
            <p>
              Percentages from different windows stay separate. Reddit's long-window domain ranking
              ran from August 2024 through late October 2025. The TechSEO Connect deck also contains
              a 90-day Reddit slice. A change between those numbers could come from time, engine
              mix, or both.
            </p>
            <p>
              Derived figures are labeled. For example, a percentage-point change calculated from
              two published percentages is shown as a calculation, not as a new measurement.
              Approximate values retain the tilde or range used in the source.
            </p>
          </div>
        </section>

        <div className="divide-y-2 divide-foreground">
          {researchArticles.map((study, studyIndex) => (
            <section key={study.slug} className="py-14">
              <p className="font-mono text-[10px] uppercase tracking-widest text-accent">
                Study 0{studyIndex + 1}
              </p>
              <h2 className="mt-3 max-w-3xl text-3xl font-display font-semibold leading-tight md:text-4xl">
                <Link
                  href={`/research/${study.slug}`}
                  className="hover:text-accent hover:underline"
                >
                  {study.title}
                </Link>
              </h2>
              <dl className="mt-8 divide-y divide-foreground/20 border-y border-foreground/20">
                <div className="grid gap-2 py-5 md:grid-cols-[10rem_1fr] md:gap-8">
                  <dt className="font-mono text-[10px] uppercase tracking-widest text-foreground/50">
                    Data source
                  </dt>
                  <dd className="font-body leading-relaxed text-foreground/80">
                    {study.methodology.dataSource}
                  </dd>
                </div>
                <div className="grid gap-2 py-5 md:grid-cols-[10rem_1fr] md:gap-8">
                  <dt className="font-mono text-[10px] uppercase tracking-widest text-foreground/50">
                    Sample size
                  </dt>
                  <dd className="font-body leading-relaxed text-foreground/80">
                    {study.methodology.sampleSize}
                  </dd>
                </div>
                <div className="grid gap-2 py-5 md:grid-cols-[10rem_1fr] md:gap-8">
                  <dt className="font-mono text-[10px] uppercase tracking-widest text-foreground/50">
                    Period
                  </dt>
                  <dd className="font-body leading-relaxed text-foreground/80">
                    {study.methodology.period}
                  </dd>
                </div>
                <div className="grid gap-2 py-5 md:grid-cols-[10rem_1fr] md:gap-8">
                  <dt className="font-mono text-[10px] uppercase tracking-widest text-foreground/50">
                    Analysis
                  </dt>
                  <dd className="font-body leading-relaxed text-foreground/80">
                    {study.methodology.approach}
                  </dd>
                </div>
                <div className="grid gap-2 py-5 md:grid-cols-[10rem_1fr] md:gap-8">
                  <dt className="font-mono text-[10px] uppercase tracking-widest text-foreground/50">
                    Published limits
                  </dt>
                  <dd className="font-body leading-relaxed text-foreground/80">
                    {study.methodology.limitations}
                  </dd>
                </div>
              </dl>
              <div className="mt-6 flex flex-wrap gap-x-6 gap-y-3 font-mono text-[10px] uppercase tracking-widest">
                {study.sources.map((source) => (
                  <a
                    key={source.url}
                    href={source.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-accent hover:underline"
                  >
                    {source.publisher} source ↗
                  </a>
                ))}
              </div>
            </section>
          ))}
        </div>

        <aside className="border-y-2 border-foreground bg-foreground px-6 py-9 text-background md:px-10">
          <p className="font-mono text-[10px] uppercase tracking-widest text-background/55">
            Corrections
          </p>
          <p className="mt-4 max-w-3xl font-body text-lg leading-relaxed">
            If a source deck or article publishes a fuller denominator later, this record should be
            updated rather than backfilled from memory. Research questions and correction notes can
            be sent to{" "}
            <a
              className="underline underline-offset-4 hover:text-accent"
              href={`mailto:${site.email}`}
            >
              {site.email}
            </a>
            .
          </p>
        </aside>
      </main>
      <Footer />
    </div>
  );
}
