import type { Appearance } from "./types";

export const appearances: readonly Appearance[] = [
  {
    id: "2026-09-shenzhen-seo",
    date: "2026-09-14",
    dateLabel: "September 14-18, 2026",
    status: "upcoming",
    title: "Field talk (title to be announced)",
    event: "Shenzhen SEO Conference 2026",
    kind: "conference",
    role: "Field-talk speaker",
    href: "https://shenzhenseoconference.com/speakers",
    location: "Shenzhen, China",
  },
  {
    id: "2026-07-15-meet-aim",
    date: "2026-07-15",
    title: "Meet Aim: The first background agent for marketing",
    event: "Profound Webinar",
    kind: "owned-event",
    role: "Lead presenter",
    href: "https://www.tryprofound.com/resources/webinars/meet-aim-the-first-background-agent-for-marketing",
    recording:
      "https://www.tryprofound.com/resources/webinars/meet-aim-the-first-background-agent-for-marketing",
    coSpeakers: ["Helen Martin"],
  },
  {
    id: "2026-07-14-mozcon",
    date: "2026-07-14",
    title: "The State of AEO in 2026",
    event: "MozCon NYC 2026",
    kind: "conference",
    role: "Solo speaker",
    href: "https://www.linkedin.com/posts/tryprofound_were-at-mozcon-next-week-and-josh-blyskal-activity-7481447512491470848-2gxR",
    location: "New York, NY",
    summary: "Research on Claude, ChatGPT ads, Google AI Mode, and Google AI Overviews.",
    slides: "https://speakerdeck.com/joshbly/the-state-of-aeo-2026",
    research: "/research/state-of-aeo-2026",
    talkFamilyId: "state-of-aeo-2026",
  },
  {
    id: "2026-07-08-state-of-aeo-webinar",
    date: "2026-07-08",
    title: "The state of AEO in 2026",
    event: "Profound Webinar",
    kind: "owned-event",
    role: "Co-presenter",
    href: "https://www.tryprofound.com/resources/webinars/the-state-of-aeo-in-2026",
    summary: "Research on Claude, ChatGPT ads, Google AI Mode, and Google AI Overviews.",
    recording: "https://www.tryprofound.com/resources/webinars/the-state-of-aeo-in-2026",
    slides: "https://speakerdeck.com/joshbly/the-state-of-aeo-2026",
    research: "/research/state-of-aeo-2026",
    coSpeakers: ["Jasman Singh"],
    talkFamilyId: "state-of-aeo-2026",
  },
  {
    id: "2026-06-11-zero-click-nyc",
    date: "2026-06-11",
    title: "The State of AEO in 2026",
    event: "Zero Click New York 2026",
    kind: "owned-event",
    role: "Co-presenter",
    href: "https://www.tryprofound.com/zeroclick/ny",
    location: "New York, NY",
    summary: "Data on ChatGPT and Claude visibility, plus an AI search advertising update.",
    recording: "https://www.tryprofound.com/zeroclick/ny",
    slides: "https://speakerdeck.com/joshbly/the-state-of-aeo-2026",
    research: "/research/state-of-aeo-2026",
    coSpeakers: ["Jasman Singh"],
    talkFamilyId: "state-of-aeo-2026",
    featuredOnHome: true,
  },
  {
    id: "2026-04-28-mach-x-toronto",
    date: "2026-04-28",
    title: "Live demo: How AI agents are making Marketing Engineering a reality",
    listTitle: "How AI agents make marketing engineering real",
    event: "MACH X Toronto - The Agentic Advantage",
    kind: "conference",
    role: "Solo presenter",
    href: "https://machalliance.org/events/mach-x-2026",
    location: "Toronto, Ontario, Canada",
    talkFamilyId: "marketing-engineering-2026",
  },
  {
    id: "2026-04-08-zero-click-sf",
    date: "2026-04-08",
    title: "The Marketing Engineer",
    event: "Zero Click San Francisco 2026",
    kind: "owned-event",
    role: "Solo speaker",
    href: "https://www.tryprofound.com/zeroclick/sf",
    location: "San Francisco, CA",
    summary: "Applying marketing engineering to answer engine optimization.",
    recording: "https://www.tryprofound.com/zeroclick/sf",
    slides: "https://www.tryprofound.com/zeroclick/sf",
    talkFamilyId: "marketing-engineering-2026",
  },
  {
    id: "2026-03-12-media-copilot",
    date: "2026-03-12",
    title: "Search is Changing Fast. Is Your Brand Ready for the Answer Engine Era?",
    listTitle: "Is your brand ready for the answer engine era?",
    event: "The Media Copilot - Season 4, Episode 7",
    kind: "podcast",
    role: "Guest",
    href: "https://mediacopilot.ai/search-is-changing-fast-is-your-brand-ready-for-the-answer-engine-era/",
    recording: "https://www.youtube.com/watch?v=Lq6UmqFjzd8",
  },
  {
    id: "2026-01-06-marketing-architects",
    date: "2026-01-06",
    title: "What Every Brand Should Know About AI Search with Josh Blyskal, Profound",
    listTitle: "What every brand should know about AI search",
    event: "The Marketing Architects - Episode 145",
    kind: "podcast",
    role: "Guest",
    href: "https://www.marketingarchitects.com/Podcast/TheMarketingArchitects/Episode145",
    recording: "https://www.youtube.com/watch?v=5E4LGiK51f4",
  },
  {
    id: "2026-01-06-format-speed",
    date: "2026-01-06",
    title: "How do I make ChatGPT recommend my product? | Josh Blyskal - Profound",
    listTitle: "How do I make ChatGPT recommend my product?",
    event: "Speed, from Format - Episode 7",
    kind: "interview",
    role: "Featured guest",
    href: "https://useformat.ai/speed/episodes/josh-blyskal",
    recording: "https://useformat.ai/speed/episodes/josh-blyskal",
  },
  {
    id: "2026-01-05-voices-of-search",
    date: "2026-01-05",
    title: "Blue Links Are Dead...Now What?",
    event: "Voices of Search",
    kind: "podcast",
    role: "Guest",
    href: "https://art19.com/shows/voices-of-search/episodes/ab7ef7db-6e97-40f9-a0da-da24b4ef829c",
    recording:
      "https://art19.com/shows/voices-of-search/episodes/ab7ef7db-6e97-40f9-a0da-da24b4ef829c",
  },
  {
    id: "2025-12-05-techseo-connect",
    date: "2025-12-05",
    title: "We Analyzed 250,000,000 AI Search Responses: Here's What We Found",
    listTitle: "What 250M AI search responses revealed",
    event: "TechSEO Connect 2025",
    kind: "conference",
    role: "Solo speaker",
    href: "https://www.tryprofound.com/blog/josh-blyskal-tech-seo-connect-deck-2025",
    location: "Raleigh, NC",
    summary:
      "Research across 250 million AI responses and 3 billion citations from eight answer engines.",
    recording: "https://www.youtube.com/watch?v=ll_kZh5GVX0",
    slides:
      "https://speakerdeck.com/joshbly/we-analyzed-250-million-ai-search-results-heres-what-i-found",
    research: "/research/250-million-ai-search-results",
    talkFamilyId: "large-scale-ai-search-research",
    featuredOnHome: true,
  },
  {
    id: "2025-12-02-fintel-connect",
    date: "2025-12-02",
    title: "LLM Playbook with Profound: How Financial Marketers Can Win in AI-Driven Discovery",
    listTitle: "An LLM playbook for financial marketers",
    event: "Fintel Connect",
    kind: "panel",
    role: "Panelist and featured expert",
    href: "https://webinars.fintelconnect.com/llm-playbook-with-profound",
    recording: "https://webinars.fintelconnect.com/llm-playbook-with-profound",
    coSpeakers: ["Nicky Senyard", "Alana Levine"],
  },
  {
    id: "2025-11-19-zero-click-london",
    date: "2025-11-19",
    title: "The Machine Customer Era",
    event: "Zero Click London 2025",
    kind: "owned-event",
    role: "Co-presenter",
    href: "https://www.tryprofound.com/resources/webinars/The-Machine-Customer-Era",
    location: "London, United Kingdom",
    summary: "How machine customers are reshaping commerce and brand visibility.",
    recording: "https://www.tryprofound.com/resources/webinars/The-Machine-Customer-Era",
    coSpeakers: ["Julia Moseyko"],
    talkFamilyId: "machine-customer-era",
  },
  {
    id: "2025-11-06-ipullrank-ai-search-to-sale",
    date: "2025-11-06",
    title: "AI Search to Sale: What the Data Reveals About AI Search eCommerce Behavior",
    listTitle: "What AI search reveals about ecommerce behavior",
    event: "iPullRank Webinar",
    kind: "webinar",
    role: "Co-presenter",
    href: "https://ipullrank.com/resources/webinars/ai-search-ecommerce-behavior-webinar",
    recording: "https://www.youtube.com/watch?v=R8A97O3XzyA",
    slides: "https://ipullrank.com/resources/webinars/ai-search-ecommerce-behavior-webinar",
    coSpeakers: ["Garrett Sussman"],
  },
  {
    id: "2025-10-08-zero-click-nyc",
    date: "2025-10-08",
    title: "The Machine Customer Era",
    event: "Zero Click New York 2025",
    kind: "owned-event",
    role: "Co-presenter",
    href: "https://www.tryprofound.com/blog/zero-click-new-york-inagaural-ai-search-nyc-summit",
    location: "New York, NY",
    summary: "How AI agents are becoming machine customers and reshaping commerce.",
    recording: "https://www.youtube.com/watch?v=pBe1BcuVqBw",
    slides: "https://speakerdeck.com/joshbly/the-machine-customer-era-zero-click-2025",
    coSpeakers: ["Sartaj Rajpal"],
    talkFamilyId: "machine-customer-era",
  },
  {
    id: "2025-10-03-suso-webinar",
    date: "2025-10-03",
    dateLabel: "Replay published October 3, 2025",
    title: "Optimizing for AI Search: The PR Agency's Tactical Playbook",
    event: "SUSO Digital AI Search Webinar Series",
    kind: "webinar",
    role: "Featured expert and co-presenter",
    href: "https://susodigital.com/thoughts/pr-agencies-tactical-playbook-ai-search-webinar/",
    recording: "https://susodigital.com/thoughts/pr-agencies-tactical-playbook-ai-search-webinar/",
    slides: "https://susodigital.com/thoughts/pr-agencies-tactical-playbook-ai-search-webinar/",
    coSpeakers: ["Cara Corbett"],
  },
  {
    id: "2025-09-29-spotlight-ar",
    date: "2025-09-29",
    dateLabel: "September 29-October 1, 2025",
    title: "If Gen AI can't find you, neither can your buyers",
    event: "Spotlight AR Summit 2025",
    kind: "conference",
    role: "Solo speaker",
    href: "https://spotlightar.com/blog/2025-ar-summit-recap-navigating-ai-elevating-ar-and-driving-business-impact/",
    location: "Kansas City, MO",
    summary: "Why analyst relations now sits at the center of B2B AI visibility.",
    recording: "https://www.youtube.com/watch?v=twkME1D_IhM",
    featuredOnHome: true,
  },
  {
    id: "2025-09-24-long-game",
    date: "2025-09-24",
    title:
      "Answer Engine Optimization Strategies & Tactics with Nick Lafferty and Josh Blyskal (Profound)",
    listTitle: "AEO strategies and tactics with Nick Lafferty",
    event: "The Long Game",
    kind: "podcast",
    role: "Guest and co-interviewee",
    href: "https://thelonggame.simplecast.com/episodes/nick-lafferty-and-josh-blyskal-BFOqUlAf",
    recording: "https://www.youtube.com/watch?v=5XUtL4r-jqQ",
    coSpeakers: ["Nick Lafferty", "Alex Birkett (host)"],
  },
  {
    id: "2025-09-24-brightonseo-san-diego",
    date: "2025-09-24",
    title: "We analyzed 40,000,000 AI search results. Here's what we found",
    event: "brightonSEO San Diego 2025",
    kind: "conference",
    role: "Solo speaker",
    href: "https://brightonseo.com/events/san-diego-2025/talks/we-analyzed-40000000-ai-search-results-heres-what-we-found",
    location: "San Diego, CA",
    summary: "Research on ChatGPT, Perplexity, and AI search patterns in US markets.",
    slides:
      "https://speakerdeck.com/joshbly/josh-blyskal-profound-i-analyzed-40-million-search-results-heres-what-i-found",
    talkFamilyId: "large-scale-ai-search-research",
  },
  {
    id: "2025-09-17-exposure-ninja",
    date: "2025-09-17",
    title: "How Fortune 500 Brands Dominate AI Search Results",
    event: "Exposure Ninja",
    kind: "webinar",
    role: "Featured expert and co-presenter",
    href: "https://exposureninja.com/webinars/fortune-500-dominate-ai-search/",
    recording: "https://www.youtube.com/watch?v=Ca1oZ9AytJY",
    coSpeakers: ["Charlie Marchant"],
  },
  {
    id: "2025-09-09-agency-insider",
    date: "2025-09-09",
    title:
      "Why Some Sites Get Cited 32.9% More in ChatGPT, Exclusive Data from Profound's Josh Blyskal",
    listTitle: "Why some sites get cited 32.9% more in ChatGPT",
    event: "The Agency Insider Show",
    kind: "podcast",
    role: "Guest",
    href: "https://www.youtube.com/watch?v=2r92accivwU",
    recording: "https://www.youtube.com/watch?v=2r92accivwU",
  },
  {
    id: "2025-07-24-mintlify-webinar",
    date: "2025-07-24",
    title: "LLMs are already reading your docs. What should you do differently?",
    listTitle: "How LLMs evaluate your documentation",
    event: "Mintlify x Profound Webinar",
    kind: "webinar",
    role: "Co-presenter",
    href: "https://www.linkedin.com/posts/dmaviles_3-months-ago-when-we-mentioned-llmstxt-activity-7349197766000091137-HTW4",
    recording: "https://streamyard.com/watch/QGcEbGysjNGw",
    coSpeakers: ["Han Wang"],
    summary:
      "How LLMs evaluate technical documentation and what teams can change to make their content easier to retrieve.",
  },
  {
    id: "2025-07-15-talking-too-loud",
    date: "2025-07-15",
    title: "How Brands Can Win in the Age of AI Search with Josh Blyskal",
    event: "Talking Too Loud with Chris Savage",
    kind: "podcast",
    role: "Guest",
    href: "https://wistia.com/series/talking-too-loud?wchannelid=9c5u5vvz1d&wmediaid=v659v090cj",
    recording:
      "https://wistia.com/series/talking-too-loud?wchannelid=9c5u5vvz1d&wmediaid=v659v090cj",
  },
  {
    id: "2025-06-30-siege-media",
    date: "2025-06-30",
    title: "AEO Playbook: How to Optimize for AI w/ Profound's Josh Blyskal",
    event: "Content and Conversation - Siege Media",
    kind: "podcast",
    role: "Guest",
    href: "https://www.siegemedia.com/conversation/aeo-playbook-how-to-optimize-for-ai-w-profounds-josh-blyskal",
    recording: "https://www.youtube.com/watch?v=GgGueQggcfU",
  },
  {
    id: "2025-06-17-aive-got-questions",
    date: "2025-06-17",
    title: "Profound with Josh Blyskal",
    event: "AI've Got Questions",
    kind: "podcast",
    role: "Guest",
    href: "https://aivegotquestions.buzzsprout.com/2497617/episodes/17355107-profound-with-josh-blyskal",
    recording:
      "https://aivegotquestions.buzzsprout.com/2497617/episodes/17355107-profound-with-josh-blyskal",
  },
  {
    id: "2025-06-05-ny-tech-week-panel",
    date: "2025-06-05",
    title: "AI Search & SEO: The New Era",
    event: "New York Tech Week by a16z",
    kind: "panel",
    role: "Panelist",
    href: "https://partiful.com/e/y8LQuI25i05ikTp6oYcv",
    location: "New York, NY",
    coSpeakers: ["Tejas Totade", "Cara Corbett", "Libby Swan (moderator)"],
  },
  {
    id: "2025-04-11-brightonseo-uk",
    date: "2025-04-11",
    title: "We analysed 10,000,000 AI search results: here's what we found",
    event: "brightonSEO April 2025",
    kind: "conference",
    role: "Solo speaker",
    href: "https://brightonseo.com/events/april-2025/talks/we-analysed-10000000-ai-search-results-heres-what-we-found",
    location: "Brighton, United Kingdom",
    summary:
      "How AI search results diverge from traditional Google results, based on 10 million results.",
    recording: "https://www.youtube.com/watch?v=slE1sgPReTM",
    slides:
      "https://speakerdeck.com/joshbly/josh-blyskal-profound-we-analyed-10000-000-ai-search-results-dot-dot-dot",
    talkFamilyId: "large-scale-ai-search-research",
    featuredOnHome: true,
  },
  {
    id: "2024-07-25-ai-hacks-science-fair",
    date: "2024-07-25",
    title: "AI in Personalized Marketing",
    event: "HubSpot Founder Focused - AI Hacks: Science Fair",
    kind: "owned-event",
    role: "Presenter",
    href: "https://community.hubspot.com/t/event-recap-ai-hacks-science-fair/131629",
    recording:
      "https://www.hubspot.com/hubfs/Founder%20Focused%20CMTY/AI%20Hacks%20Science%20Fair.mp4",
  },
  {
    id: "2023-09-14-ai-prompt-engineering",
    date: "2023-09-14",
    title: "AI Prompt Engineering",
    event: "Howard University Center for Digital Business / HubSpot",
    kind: "workshop",
    role: "Presenter and workshop leader",
    href: "https://www.hucdb.com/ai-engineering-hubspot",
  },
  {
    id: "2023-06-28-hubspot-master-marketing-prompts",
    date: "2023-06-28",
    title: "Live Workshop: Master Marketing Prompts and Unlock the Power of AI",
    listTitle: "Master marketing prompts with HubSpot",
    event: "HubSpot Prompt Practitioners",
    kind: "workshop",
    role: "Instructor and AI marketing expert",
    href: "https://offers.hubspot.com/prompt-practitioners-kick-off",
  },
];
