import type { LinkedInPost } from "./types";

export const linkedinPosts: readonly LinkedInPost[] = [
  {
    id: "daily-prompt-measurement",
    date: "2026-07-08",
    title: "Is running each AI prompt once per day enough?",
    listTitle: "Is one AI prompt run per day enough?",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_is-running-the-same-ai-prompt-once-a-day-activity-7480696857871155200-2JlF",
  },
  {
    id: "claude-chatgpt-domain-overlap",
    date: "2026-07-06",
    title: "Claude and ChatGPT share only 8% of cited domains",
    listTitle: "Claude and ChatGPT share 8% of domains",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_claude-and-chatgpt-only-cite-the-same-domains-activity-7479957866943193088-XB_D",
    relatedWorkId: "state-of-aeo-2026",
  },
  {
    id: "claude-brave-top-ten",
    date: "2026-06-15",
    title: "79.2% of Claude citations come from Brave's top 10",
    listTitle: "79.2% of Claude citations use Brave",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_792-of-claudes-citations-come-from-braves-activity-7472323829604995073-35e-",
    relatedWorkId: "state-of-aeo-2026",
  },
  {
    id: "chatgpt-reddit-search-growth",
    date: "2026-06-02",
    title: "ChatGPT began explicitly searching for Reddit 24× more often",
    listTitle: "ChatGPT searches for Reddit 24× more",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_chatgpt-is-explicitly-searching-for-reddit-activity-7467567489535700993-oM4W",
  },
  {
    id: "chatgpt-referral-traffic-growth",
    date: "2026-05-20",
    title: "ChatGPT referral traffic to brand sites rose roughly 60%",
    listTitle: "ChatGPT referral traffic rose 60%",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_chatgpt-referral-traffic-to-brand-websites-activity-7462845835765141504-nffV",
  },
  {
    id: "time-to-first-ai-citation",
    date: "2026-05-11",
    title: "Median time to first ChatGPT or Claude citation is 6.81 days",
    listTitle: "First AI citation takes 6.81 days",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_how-long-does-it-take-to-get-cited-in-chatgpt-activity-7459597424102223873-Ywuj",
  },
  {
    id: "marketing-engineer-role",
    date: "2026-04-16",
    title: "The word is Marketing Engineer",
    kind: "essay",
    href: "https://www.linkedin.com/posts/joshua-blyskal_you-know-that-person-on-your-marketing-team-activity-7450544556300947456-JQBe",
  },
  {
    id: "earned-media-tier-one-citations",
    date: "2026-02-06",
    title: "Only 2.6% of earned-media citations come from Tier 1 publications",
    listTitle: "Tier 1 earns 2.6% of AI citations",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_only-26-of-earned-media-citations-in-ai-activity-7425494219974311936-Z_2c",
  },
  {
    id: "blogs-opinion-ai-citations",
    date: "2026-02-06",
    title: "Blogs and opinion overtook listicles in AI citations",
    listTitle: "Blogs overtook listicles in AI citations",
    kind: "analysis",
    href: "https://www.linkedin.com/posts/joshua-blyskal_want-to-pile-on-here-because-weve-been-seeing-activity-7425668809157419008-czyc",
  },
  {
    id: "chatgpt-web-search-by-intent",
    date: "2026-01-08",
    title: "When ChatGPT searches the web, segmented by intent",
    listTitle: "When ChatGPT searches the web",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_i-pulled-667k-chatgpt-conversations-from-activity-7415035320527683584-vOgG",
  },
  {
    id: "inspect-chatgpt-network-logs",
    date: "2025-11-25",
    title: "How to inspect ChatGPT network logs",
    kind: "tutorial",
    href: "https://www.linkedin.com/posts/joshua-blyskal_everyone-in-aeogeo-should-know-how-to-do-activity-7399096886990897152-Udvx",
  },
  {
    id: "serp-influence-fanout-sequence",
    date: "2025-11-11",
    title: "SERP influence decays through ChatGPT's fanout sequence",
    listTitle: "SERP influence fades through fanout",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_we-just-completed-one-of-the-worlds-most-activity-7394014625547067393-z2Fc",
  },
  {
    id: "ai-shopping-consumer-study",
    date: "2025-11-03",
    title: "How 2,739 consumers use AI for shopping",
    listTitle: "How 2,739 people shop with AI",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_ive-been-analyzing-how-people-use-ai-for-activity-7391189515362791424-jt7d",
  },
  {
    id: "atlas-agent-usability",
    date: "2025-10-21",
    title: "Atlas shifts optimization from discovery to agent usability",
    listTitle: "Atlas shifts SEO toward agent usability",
    kind: "analysis",
    href: "https://www.linkedin.com/posts/joshua-blyskal_i-spent-some-time-in-the-network-logs-of-activity-7386497765968596994-AXE7",
  },
  {
    id: "reddit-citation-collapse-recovery",
    date: "2025-10-21",
    title: "Reddit's ChatGPT citation collapse and recovery",
    listTitle: "Reddit's ChatGPT citation collapse",
    kind: "analysis",
    href: "https://www.linkedin.com/posts/joshua-blyskal_theres-been-a-lot-of-chatting-lately-about-activity-7386410380018860032-QMAr",
  },
  {
    id: "etsy-instant-checkout-variants",
    date: "2025-10-06",
    title: "Instant Checkout fails for Etsy products with variants",
    listTitle: "Instant Checkout fails on Etsy variants",
    kind: "experiment",
    href: "https://www.linkedin.com/posts/joshua-blyskal_openais-instant-checkout-is-live-on-etsy-activity-7380943609719693312--_H5",
  },
  {
    id: "chatgpt-memory-search-pipelines",
    date: "2025-10-03",
    title: "ChatGPT memories and web search use mostly separate pipelines",
    listTitle: "ChatGPT memory and search stay separate",
    kind: "experiment",
    href: "https://www.linkedin.com/posts/joshua-blyskal_quick-hit-discovered-today-that-memories-activity-7379973286782193664-ylQx",
  },
  {
    id: "instant-checkout-product-feed",
    date: "2025-09-29",
    title: "OpenAI Instant Checkout's product-feed opportunity",
    listTitle: "Instant Checkout needs product feeds",
    kind: "analysis",
    href: "https://www.linkedin.com/posts/joshua-blyskal_openai-just-launched-instant-checkout-i-activity-7378508559774351361-ocfl",
  },
  {
    id: "chatgpt-information-seeking-growth",
    date: "2025-09-20",
    title: "Information-seeking grew from 14% to 24% of ChatGPT use",
    listTitle: "Information seeking hit 24% in ChatGPT",
    kind: "analysis",
    href: "https://www.linkedin.com/posts/joshua-blyskal_one-interesting-finding-from-chatgpts-usage-activity-7375209711509475328-A-gF",
  },
  {
    id: "commercial-prompt-price-constraints",
    date: "2025-09-18",
    title: "One-quarter of commercial prompts begin with a price constraint",
    listTitle: "25% of buying prompts start with price",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_openai-released-their-intent-study-with-activity-7374417160208793600-scaT",
  },
  {
    id: "chatgpt-referral-traffic-decline",
    date: "2025-08-20",
    title: "ChatGPT referral traffic fell 52%",
    kind: "analysis",
    href: "https://www.linkedin.com/posts/joshua-blyskal_chatgpt-referral-traffic-is-down-52-since-activity-7364003556087005185-BaJ0",
  },
  {
    id: "bluffed-way-into-profound",
    date: "2025-08-12",
    title: "I bluffed my way into my job at Profound",
    listTitle: "How I bluffed my way into Profound",
    kind: "essay",
    href: "https://www.linkedin.com/posts/joshua-blyskal_i-bluffed-my-way-into-my-job-at-profound-activity-7361135138400813057-9arb",
  },
  {
    id: "gpt-5-browsing-tests",
    date: "2025-08-08",
    title: "First-pass tests of GPT-5 browsing",
    kind: "experiment",
    href: "https://www.linkedin.com/posts/joshua-blyskal_took-some-time-tn-to-do-some-tests-on-gpt-activity-7359403005609140224-5ibL",
  },
  {
    id: "google-rank-chatgpt-citations",
    date: "2025-07-31",
    title: "Google positions 4–10 remain viable for ChatGPT citations",
    listTitle: "Google positions 4–10 still earn citations",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_positions-4-10-are-viable-real-estate-for-activity-7356700449950822400-G0t8",
  },
  {
    id: "google-ai-mode-citation-findings",
    date: "2025-07-09",
    title: "Three findings from 19 million Google AI Mode citations",
    listTitle: "Three findings from 19M AI Mode citations",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_3-ai-search-insights-in-one-day-i-spent-activity-7348727459229454337-YKZn",
  },
  {
    id: "accessible-health-information",
    date: "2025-06-10",
    title: "How AI prioritizes accessible health information over institutional authority",
    listTitle: "AI favors accessible health information",
    kind: "analysis",
    href: "https://www.linkedin.com/posts/joshua-blyskal_this-data-completely-flipped-my-assumptions-activity-7338259826528968704-4p9C",
  },
  {
    id: "reddit-citation-growth",
    date: "2025-06-04",
    title: "Reddit citations rose 436% in ChatGPT",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_reddit-citations-are-up-400-in-chatgpt-activity-7336057282968920068-m8cA",
  },
  {
    id: "wikipedia-ai-citations",
    date: "2025-05-15",
    title: "Wikipedia's share across 534 million AI citations",
    listTitle: "Wikipedia's share of 534M AI citations",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_i-pulled-534-million-citations-from-chatgpt-activity-7328834362446090241-FXtf",
  },
  {
    id: "backlinks-ai-citations",
    date: "2025-05-12",
    title: "Sites with fewer backlinks were cited more often",
    listTitle: "Fewer backlinks, more AI citations",
    kind: "research",
    href: "https://www.linkedin.com/posts/joshua-blyskal_backlinks-do-have-a-relationship-with-ai-activity-7327705645661544450-ZxBA",
  },
  {
    id: "guides-citation-share",
    date: "2025-03-20",
    title: "Citation share after moving top-cited posts into /guides",
    listTitle: "Moving cited posts into /guides",
    kind: "experiment",
    href: "https://www.linkedin.com/posts/joshua-blyskal_profounds-own-citation-share-before-and-activity-7308289896299855872-cOW6",
  },
  {
    id: "startup-moat",
    date: "2025-02-02",
    title: "One trench stops nothing. A thousand is a moat",
    listTitle: "A thousand trenches make a moat",
    kind: "essay",
    href: "https://www.linkedin.com/posts/joshua-blyskal_having-been-at-a-startup-for-a-few-months-activity-7291620097289248769-lTyO",
  },
  {
    id: "chained-llm-email-system",
    date: "2024-09-24",
    title: "How a chained-LLM email system increased conversion 82%",
    listTitle: "Chained LLM emails lifted conversion 82%",
    kind: "case-study",
    href: "https://www.linkedin.com/posts/joshua-blyskal_inbound24-marketing-ai-activity-7244318432089837568-Cwry",
  },
  {
    id: "ai-search-grader-launch",
    date: "2024-08-13",
    title: "AI Search Grader launch and why AI visibility needs a dedicated tool",
    listTitle: "Why AI visibility needed its own grader",
    kind: "essay",
    href: "https://www.linkedin.com/posts/joshua-blyskal_ai-search-grader-2025-activity-7229195829696172032-IY4b",
  },
];

export const linkedinArchiveNote = "Publicly indexed posts through July 26, 2026.";
