import type { PressRecord } from "./types";

export const pressRecords: readonly PressRecord[] = [
  {
    id: "state-of-brand-margin-of-error",
    date: "2026-07-20",
    title: "Two AI-Search Startups Are Arguing About Margins of Error",
    outlet: "State of Brand",
    domain: "thestateofbrand.com",
    kind: "research-cited",
    href: "https://www.thestateofbrand.com/news/ai-visibility-measurement-margin-of-error",
  },
  {
    id: "adweek-profound-ai-agent",
    date: "2026-07-02",
    title: "Profound Launches an AI Agent to Manage End-to-End Marketing",
    outlet: "Adweek",
    domain: "adweek.com",
    kind: "quoted",
    href: "https://www.adweek.com/media/profound-launches-an-ai-agent-to-manage-end-to-end-marketing/",
    featuredOnHome: true,
  },
  {
    id: "search-engine-land-seven-ai-search-shifts",
    date: "2026-06-17",
    title: "7 AI search shifts you can't afford to ignore",
    outlet: "Search Engine Land",
    domain: "searchengineland.com",
    kind: "research-cited",
    href: "https://searchengineland.com/ai-search-shifts-you-cant-ignore-480381",
  },
  {
    id: "complexdiscovery-ai-advisor",
    date: "2026-06-08",
    title: "AI is becoming an advisor, and it is rewriting how buyers find you",
    outlet: "ComplexDiscovery",
    domain: "complexdiscovery.com",
    kind: "research-cited",
    href: "https://complexdiscovery.com/ai-is-becoming-an-advisor-and-it-is-rewriting-how-buyers-find-you/",
  },
  {
    id: "adexchanger-openai-app",
    date: "2026-03-13",
    title: "A Third-Party Promo Gone Awry; OpenAI Has An App For That",
    outlet: "AdExchanger",
    domain: "adexchanger.com",
    kind: "quoted",
    href: "https://www.adexchanger.com/daily-news-roundup/friday-13032026/",
  },
  {
    id: "the-information-shopping-apps",
    date: "2026-03-11",
    title: "OpenAI's Shift to Shopping Apps Faces Even More Hurdles",
    outlet: "The Information",
    domain: "theinformation.com",
    kind: "quoted",
    href: "https://www.theinformation.com/articles/openais-betting-chatgpt-apps-people-need-find-first",
  },
  {
    id: "previsible-answer-engine-optimization",
    date: "2026-01-09",
    title: "Answer Engine Optimization Is the New SEO Strategy",
    outlet: "Previsible",
    domain: "previsible.io",
    kind: "quoted",
    href: "https://previsible.io/seo-ai-news/the-death-of-blue-links/",
  },
  {
    id: "adexchanger-ai-search-reckoning",
    date: "2026-01-06",
    title:
      "The AI Search Reckoning Is Dismantling Open Web Traffic – And Publishers May Never Recover",
    outlet: "AdExchanger",
    domain: "adexchanger.com",
    kind: "quoted",
    href: "https://www.adexchanger.com/publishers/the-ai-search-reckoning-is-dismantling-open-web-traffic-and-publishers-may-never-recover/",
  },
  {
    id: "lift-labs-geo-agentic-commerce",
    date: "2026-01-01",
    dateLabel: "Jan 2026",
    title: "GEO, Agentic Commerce and how AI is Redefining Consumer-Brand Relationships",
    outlet: "Comcast NBCUniversal LIFT Labs",
    domain: "lift.comcast.com",
    kind: "quoted",
    href: "https://lift.comcast.com/wp-content/uploads/2026/01/LIFT-LABS-GEO-SEO-White-Paper.pdf",
  },
  {
    id: "expert-seo-consulting-answer-engines",
    date: "2025-12-22",
    title: "Answer Engines Arbitrate the Relationship: Josh Blyskal's AEO Data",
    outlet: "Expert SEO Consulting",
    domain: "expertseoconsulting.com",
    kind: "research-cited",
    href: "https://expertseoconsulting.com/answer-engines-arbitrate-the-relationship-josh-blyskals-aeo-data-at-tech-seo-connect/",
  },
  {
    id: "the-verge-new-internet",
    date: "2025-12-10",
    title: "AI companies want a new internet, and they think they've found the key",
    outlet: "The Verge",
    domain: "theverge.com",
    kind: "quoted",
    href: "https://www.theverge.com/ai-artificial-intelligence/841156/ai-companies-aaif-anthropic-mcp-model-context-protocol",
    featuredOnHome: true,
  },
  {
    id: "search-engine-land-social-ugc",
    date: "2025-11-04",
    title: "Social and UGC: The trust engines powering search everywhere",
    outlet: "Search Engine Land",
    domain: "searchengineland.com",
    kind: "quoted",
    href: "https://searchengineland.com/social-ugc-trust-engines-powering-search-everywhere-464101",
  },
  {
    id: "ad-age-chatgpt-atlas",
    date: "2025-10-23",
    title: "ChatGPT's new AI browser Atlas: what brands need to know",
    outlet: "Ad Age",
    domain: "adage.com",
    kind: "quoted",
    href: "https://adage.com/technology/ai/aa-chatgpt-browser-atlas-brands/",
    alternateLinks: [
      {
        label: "Meio & Mensagem",
        href: "https://www.meioemensagem.com.br/midia/atlas-do-chatgpt-acende-alerta-para-agencias-e-anunciantes",
      },
    ],
    featuredOnHome: true,
  },
  {
    id: "retail-touchpoints-instant-checkout",
    date: "2025-10-01",
    title: "What ChatGPT's 'Instant Checkout' Offering Means for Retailers",
    outlet: "Retail TouchPoints",
    domain: "retailtouchpoints.com",
    kind: "research-cited",
    href: "https://www.retailtouchpoints.com/features/industry-insights/what-chatgpts-instant-checkout-offering-means-for-retailers",
  },
  {
    id: "business-of-fashion-geo-beauty",
    date: "2025-08-26",
    title: "'GEO' Is Beauty's New 'SEO'",
    outlet: "Business of Fashion",
    domain: "businessoffashion.com",
    kind: "quoted",
    href: "https://www.businessoffashion.com/articles/beauty/geo-is-beautys-new-seo/",
    featuredOnHome: true,
  },
  {
    id: "tech-edition-chatgpt-referrals",
    date: "2025-08-26",
    title: "ChatGPT referral traffic to websites drops by 52% in one month",
    outlet: "Tech Edition",
    domain: "techedt.com",
    kind: "research-cited",
    href: "https://www.techedt.com/chatgpt-referral-traffic-to-websites-drops-by-52-in-one-month",
  },
  {
    id: "search-engine-roundtable-chatgpt-referrals",
    date: "2025-08-21",
    title: "Report: OpenAI ChatGPT Sending 52% Less Referral Traffic",
    outlet: "Search Engine Roundtable",
    domain: "seroundtable.com",
    kind: "research-cited",
    href: "https://www.seroundtable.com/openai-chatgpt-52-less-referral-traffic-39977.html",
  },
  {
    id: "search-engine-land-chatgpt-referrals",
    date: "2025-08-20",
    title: "ChatGPT is sending less traffic to websites – down 52% in a month",
    outlet: "Search Engine Land",
    domain: "searchengineland.com",
    kind: "research-cited",
    href: "https://searchengineland.com/chatgpt-traffic-referrals-plummet-461027",
    alternateLinks: [
      {
        label: "MarTech",
        href: "https://martech.org/chatgpt-traffic-to-websites-is-down-52-in-a-month/",
      },
    ],
    featuredOnHome: true,
  },
  {
    id: "ppc-land-chatgpt-referrals",
    date: "2025-08-20",
    title: "ChatGPT referral traffic drops 52% as citation patterns shift dramatically",
    outlet: "PPC Land",
    domain: "ppc.land",
    kind: "research-cited",
    href: "https://ppc.land/chatgpt-referral-traffic-drops-52-as-citation-patterns-shift-dramatically/",
  },
  {
    id: "techbullion-geo-experts",
    date: "2025-08-15",
    title: "The Definitive Guide to Generative Engine Optimization Experts in 2025",
    outlet: "TechBullion",
    domain: "techbullion.com",
    kind: "research-cited",
    href: "https://techbullion.com/definitive-guide-generative-engine-optimization-experts-2025/",
  },
  {
    id: "bcg-future-of-discoverability",
    date: "2025-05-13",
    title: "The Future of Discoverability",
    outlet: "BCG",
    domain: "bcg.com",
    kind: "quoted",
    href: "https://www.bcg.com/x/the-multiplier/the-future-of-discoverability",
    featuredOnHome: true,
  },
  {
    id: "search-engine-land-brand-visibility",
    date: "2024-11-27",
    title: "How to monitor brand visibility across AI search channels",
    outlet: "Search Engine Land",
    domain: "searchengineland.com",
    kind: "quoted",
    href: "https://searchengineland.com/monitor-brand-visibility-ai-search-channels-448697",
  },
];
